language: generic 
sudo: required
services:
  - docker

before_install:
  - docker build -t thanhld97/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true thanhld97/docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "ap-southeast-1"
  app: "docker_react"
  env: "Dockerreact-env"
  bucket_name: "elasticbeanstalk-ap-southeast-1-206276806578"
  bucket_path: "docker_react"
  on:
    branch: main
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY